// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqroqPb2-bIKSZsytkHj6JIgNOkStkcsU',
    appId: '1:536746077626:web:4f19996f760c06e1e98183',
    messagingSenderId: '536746077626',
    projectId: 'drop-1111',
    authDomain: 'drop-1111.firebaseapp.com',
    storageBucket: 'drop-1111.appspot.com',
    measurementId: 'G-XFGG2WZW00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lP8exURIYenFN6rFSsPyYit0wab3wH8',
    appId: '1:536746077626:android:ab8849ba2f41908be98183',
    messagingSenderId: '536746077626',
    projectId: 'drop-1111',
    storageBucket: 'drop-1111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrU096uR5ZDX2qhN753mPlbmnh_1yup9Y',
    appId: '1:536746077626:ios:889350fe74556ce3e98183',
    messagingSenderId: '536746077626',
    projectId: 'drop-1111',
    storageBucket: 'drop-1111.appspot.com',
    iosClientId: '536746077626-lb70ub6n6q9no1oatpd5lfdk0aogt8vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.allDrop',
  );
}
